In [109]:
import pandas as pd

In [110]:
import openpyxl
data = pd.read_excel("marriage_dataset_v2.xlsx")
data.head()

,Name,Age,Gender,Religion,Education,Annual_Income,Location_Type,Partner_Name,Partner_Age,Partner_Gender,...,Partner_Education,Partner_Annual_Income,Partner_Location_Type,Years_Together,Age_Difference,Intercaste,Are_They_Happy,Want_To_Marry,Compatibility_Score,Married
0,Anil Srivastava,42,Male,Hindu,Below 10th,2-5L,Urban,Sunita Kumar,20,Female,...,12th Pass,20-50L,Semi-Urban,13.1,22,No,Yes,Yes,100,Yes
1,Vishal Sharma,55,Male,Hindu,10th Pass,<2L,Rural,Pooja Kapoor,41,Female,...,Post Graduate,<2L,Urban,6.7,14,No,Yes,Yes,100,Yes
2,Mansi Yadav,33,Female,Hindu,Below 10th,>50L,Rural,Manish Agarwal,18,Male,...,12th Pass,5-10L,Urban,4.3,15,No,Yes,No,76,Yes
3,Aarav Gupta,33,Male,Hindu,Graduate,5-10L,Rural,Seema Agarwal,55,Female,...,Graduate,20-50L,Urban,5.2,22,No,Yes,No,92,Yes
4,Ritika Naidu,39,Female,Hindu,PhD,10-20L,Urban,Sandeep Rajput,49,Male,...,Post Graduate,<2L,Semi-Urban,13.6,10,Yes,Yes,Yes,88,Yes

In [111]:
data = data.drop(columns=['Name', 'Partner_Name', 'Education', 'Partner_Education', 'Annual_Income', 'Partner_Annual_Income'])
data

,Age,Gender,Religion,Location_Type,Partner_Age,Partner_Gender,Partner_Religion,Partner_Location_Type,Years_Together,Age_Difference,Intercaste,Are_They_Happy,Want_To_Marry,Compatibility_Score,Married
0,42,Male,Hindu,Urban,20,Female,Hindu,Semi-Urban,13.1,22,No,Yes,Yes,100,Yes
1,55,Male,Hindu,Rural,41,Female,Hindu,Urban,6.7,14,No,Yes,Yes,100,Yes
2,33,Female,Hindu,Rural,18,Male,Hindu,Urban,4.3,15,No,Yes,No,76,Yes
3,33,Male,Hindu,Rural,55,Female,Hindu,Urban,5.2,22,No,Yes,No,92,Yes
4,39,Female,Hindu,Urban,49,Male,Hindu,Semi-Urban,13.6,10,Yes,Yes,Yes,88,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,30,Male,Hindu,Rural,45,Female,Hindu,Semi-Urban,14.4,15,No,Yes,Yes,100,Yes
9996,21,Male,Hindu,Urban,40,Female,Hindu,Semi-Urban,3.2,19,No,Yes,Yes,100,Yes
9997,52,Female,Hindu,Semi-Urban,46,Male,Hindu,Urban,1.3,6,No,No,Yes,86,Yes
9998,50,Female,Muslim,Urban,25,Male,Muslim,Urban,2.1,25,Yes,No,Yes,81,No
9999,19,Female,Hindu,Urban,26,Male,Hindu,Urban,14.0,7,Yes,No,Yes,77,Yes

In [112]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])
data['Partner_Gender'] = label_encoder.fit_transform(data['Partner_Gender'])
data['Intercaste'] = label_encoder.fit_transform(data['Intercaste'])
data['Are_They_Happy'] = label_encoder.fit_transform(data['Are_They_Happy'])
data['Want_To_Marry']= label_encoder.fit_transform(data['Want_To_Marry'])
data['Married']= label_encoder.fit_transform(data['Married'])
data

,Age,Gender,Religion,Location_Type,Partner_Age,Partner_Gender,Partner_Religion,Partner_Location_Type,Years_Together,Age_Difference,Intercaste,Are_They_Happy,Want_To_Marry,Compatibility_Score,Married
0,42,1,Hindu,Urban,20,0,Hindu,Semi-Urban,13.1,22,0,1,1,100,1
1,55,1,Hindu,Rural,41,0,Hindu,Urban,6.7,14,0,1,1,100,1
2,33,0,Hindu,Rural,18,1,Hindu,Urban,4.3,15,0,1,0,76,1
3,33,1,Hindu,Rural,55,0,Hindu,Urban,5.2,22,0,1,0,92,1
4,39,0,Hindu,Urban,49,1,Hindu,Semi-Urban,13.6,10,1,1,1,88,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,30,1,Hindu,Rural,45,0,Hindu,Semi-Urban,14.4,15,0,1,1,100,1
9996,21,1,Hindu,Urban,40,0,Hindu,Semi-Urban,3.2,19,0,1,1,100,1
9997,52,0,Hindu,Semi-Urban,46,1,Hindu,Urban,1.3,6,0,0,1,86,1
9998,50,0,Muslim,Urban,25,1,Muslim,Urban,2.1,25,1,0,1,81,0
9999,19,0,Hindu,Urban,26,1,Hindu,Urban,14.0,7,1,0,1,77,1

In [113]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder()
encoder = onehot_encoder.fit_transform(data[['Religion', 'Partner_Religion', 'Location_Type', 'Partner_Location_Type']])
onehot_encoder.get_feature_names_out(['Religion', 'Partner_Religion', 'Location_Type', 'Partner_Location_Type'])

array(['Religion_Buddhist', 'Religion_Christian', 'Religion_Hindu',
       'Religion_Jain', 'Religion_Muslim', 'Religion_Parsi',
       'Religion_Sikh', 'Partner_Religion_Buddhist',
       'Partner_Religion_Christian', 'Partner_Religion_Hindu',
       'Partner_Religion_Jain', 'Partner_Religion_Muslim',
       'Partner_Religion_Parsi', 'Partner_Religion_Sikh',
       'Location_Type_Rural', 'Location_Type_Semi-Urban',
       'Location_Type_Urban', 'Partner_Location_Type_Rural',
       'Partner_Location_Type_Semi-Urban', 'Partner_Location_Type_Urban'],
      dtype=object)

In [114]:
onehot_encoded_df = pd.DataFrame(encoder.toarray(), columns=onehot_encoder.get_feature_names_out(['Religion', 'Partner_Religion', 'Location_Type', 'Partner_Location_Type']))
onehot_encoded_df

,Religion_Buddhist,Religion_Christian,Religion_Hindu,Religion_Jain,Religion_Muslim,Religion_Parsi,Religion_Sikh,Partner_Religion_Buddhist,Partner_Religion_Christian,Partner_Religion_Hindu,Partner_Religion_Jain,Partner_Religion_Muslim,Partner_Religion_Parsi,Partner_Religion_Sikh,Location_Type_Rural,Location_Type_Semi-Urban,Location_Type_Urban,Partner_Location_Type_Rural,Partner_Location_Type_Semi-Urban,Partner_Location_Type_Urban
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
9996,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
9997,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
9998,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
9999,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [115]:
data = pd.concat([data.drop(['Religion', 'Partner_Religion', 'Location_Type', 'Partner_Location_Type'], axis=1), onehot_encoded_df], axis=1)
data

,Age,Gender,Partner_Age,Partner_Gender,Years_Together,Age_Difference,Intercaste,Are_They_Happy,Want_To_Marry,Compatibility_Score,...,Partner_Religion_Jain,Partner_Religion_Muslim,Partner_Religion_Parsi,Partner_Religion_Sikh,Location_Type_Rural,Location_Type_Semi-Urban,Location_Type_Urban,Partner_Location_Type_Rural,Partner_Location_Type_Semi-Urban,Partner_Location_Type_Urban
0,42,1,20,0,13.1,22,0,1,1,100,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,55,1,41,0,6.7,14,0,1,1,100,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,33,0,18,1,4.3,15,0,1,0,76,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,33,1,55,0,5.2,22,0,1,0,92,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,39,0,49,1,13.6,10,1,1,1,88,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,30,1,45,0,14.4,15,0,1,1,100,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
9996,21,1,40,0,3.2,19,0,1,1,100,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
9997,52,0,46,1,1.3,6,0,0,1,86,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
9998,50,0,25,1,2.1,25,1,0,1,81,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
9999,19,0,26,1,14.0,7,1,0,1,77,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [116]:
import pickle
with open('serialized_object/label_encoder.pkl', 'wb') as file:
    pickle.dump(label_encoder, file)
with open('serialized_object/onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot_encoder, file)

with open('proccessed_data.pkl', 'wb') as file:
    pickle.dump(data,file)

In [117]:
data.head(1)

,Age,Gender,Partner_Age,Partner_Gender,Years_Together,Age_Difference,Intercaste,Are_They_Happy,Want_To_Marry,Compatibility_Score,...,Partner_Religion_Jain,Partner_Religion_Muslim,Partner_Religion_Parsi,Partner_Religion_Sikh,Location_Type_Rural,Location_Type_Semi-Urban,Location_Type_Urban,Partner_Location_Type_Rural,Partner_Location_Type_Semi-Urban,Partner_Location_Type_Urban
0,42,1,20,0,13.1,22,0,1,1,100,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [118]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = data.drop('Married', axis=1)
Y = data['Married']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [119]:
with open('serialized_object/scalar.pkl', 'wb') as file:
    pickle.dump(scalar, file)

In [120]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.pipeline import Pipeline
from scikeras.wrappers import KerasClassifier

In [121]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.pipeline import Pipeline
from scikeras.wrappers import KerasClassifier

In [122]:
def create_model(neurons=64, layer=2):
    model = Sequential()
    model.add(Dense(neurons, activation='relu', input_shape=(X_train.shape[1],)))
    for _ in range(layer - 1):
        model.add(Dense(neurons, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [123]:
## create a keras classifier
model = KerasClassifier(model=create_model, epochs=10, batch_size=10, verbose=0, neurons=32, layer=2)

In [124]:
#Define Grid Search parameters
from sklearn.model_selection import GridSearchCV
param_grid = {
    'neurons': [ 32, 64],
    'layer': [2, 3],
    'epochs': [50, 100],
    'batch_size': [10, 20]
}

In [125]:
#perform grid search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(X_train, Y_train)

# summarize results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
##Best: 0.9506252641150539 using {'batch_size': 10, 'epochs': 50, 'layer': 2, 'neurons': 32}

c:\Users\rajes\miniconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Best: 0.9508749984646517 using {'batch_size': 20, 'epochs': 50, 'layer': 2, 'neurons': 64}